### PR TITLE
Setup precommit hook

### PR DESCRIPTION
**Pull request by abhinav1912**
1. Create a central/single `requirements.txt` file
2. Added pre-commit hook and `black` formatter

### CODE REVIEW

**Review by prothy — APPROVED** [review]
`pre-commit` can be used for any hooks, right?

**Comment by abhinav1912** [comment]
@prothy yes

**Comment by CollectiveFocus** [comment]
For future tickets could we follow the workflow we agreed on:

1. Assign yourself the Trello ticket
2. Move the Trello Ticket to the appropriate Trello column
3. Name the branch TICKET_ID_[DEV_INITIAL] so for this ticket CFM_68_AM

I do like how you named your branch though, its informative.  So if you would like to suggest a different naming convention I'm fine with that too. But it would be good to have the ticket id somewhere in the branch name :)

**Review by CollectiveFocus — APPROVED** [review]
Looks good to me! Thank you :)

**Comment by abhinav1912** [comment]
> For future tickets could we follow the workflow we agreed on:
> 
> 1. Assign yourself the Trello ticket
> 2. Move the Trello Ticket to the appropriate Trello column
> 3. Name the branch TICKET_ID_[DEV_INITIAL] so for this ticket CFM_68_AM
> 
> I do like how you named your branch though, its informative. So if you would like to suggest a different naming convention I'm fine with that too. But it would be good to have the ticket id somewhere in the branch name :)

What we can do is, organise the branches by username. So branch names will have the format `user/{user_initials}_{ticket_number}/{small_description}`.
Eg: branch name for this branch would become `user/AM_68/setup_precommit_hook`

**Comment by prothy** [comment]
> > For future tickets could we follow the workflow we agreed on:
> > 
> > 1. Assign yourself the Trello ticket
> > 2. Move the Trello Ticket to the appropriate Trello column
> > 3. Name the branch TICKET_ID_[DEV_INITIAL] so for this ticket CFM_68_AM
> > 
> > I do like how you named your branch though, its informative. So if you would like to suggest a different naming convention I'm fine with that too. But it would be good to have the ticket id somewhere in the branch name :)
> 
> What we can do is, organise the branches by username. So branch names will have the format `user/{user_initials}_{ticket_number}/{small_description}`. Eg: branch name for this branch would become `user/AM_68/setup_precommit_hook`

I do like that, but I think we can simplify a bit further, even. Something like `am-68/setup-precommit-hook`. Often there's a `feat/`, `fix/` prefix added on too, but I always thought that was a bit superficial. The ticket has any additional info, if needed.

Anyway, I would bring it up on the Discord channel, see what the others have to say.

**Pull request merged**
